spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true

  devtools:
    livereload:
      enabled: true
  profiles:
    include: db


server:
  port: 8005